---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        args: ["--max-line-length", "99"]
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--line-length", "99", "--preview"]
  - repo: local
    hooks:
      - id: run-mypy
        name: Run mypy
        entry: make mypy
        language: system
        pass_filenames: false
