---
flowehr_id: REPLACE_ME
location: REPLACE_ME
environment: dev

transform:
  spark_version: 3.4
  repositories:
    - url: https://github.com/SAFEHR-hdata/Data-Seedling.git
  datalake:
    zones:
      - bronze
      - silver
      - gold
      - internal
  unity_catalog:
    catalog_name: catalog
    schema_name: schema
    datalake_zones:
      - gold

  unity_catalog_metastore:
    metastore_name: metastore
    storage_account_name: REPLACE_ME
    resource_group_name:  REPLACE_ME

  spark_config:
    spark.databricks.delta.properties.defaults.enableChangeDataFeed: "true"

  databricks_account_id: REPLACE_ME 
  databricks_libraries:
    pypi:
      - package: opencensus-ext-azure==1.1.9
      - package: opencensus-ext-logging==0.1.1
      - package: presidio-analyzer==2.2.33
      - package: presidio-anonymizer==2.2.33
      - package: synapseml==0.11.2
      - package: https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.6.0/en_core_web_lg-3.6.0-py3-none-any.whl
    maven:
      - coordinates: "com.microsoft.azure:synapseml_2.12:0.11.2-spark3.3"
        repo: "https://mmlspark.azureedge.net/maven"
  databricks_cluster:
    autotermination_minutes: 60
    num_of_workers: 1
    data_security_mode: SINGLE_USER
  databricks_secrets:
    cognitive-services-keys: REPLACE_ME 
    cognitive-services-location: REPLACE_ME
    azure-tenant-id: REPLACE_ME 
