[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dataset_provisioning"
version = "0.0.1"
dependencies = []

[project.optional-dependencies]
lint = [
    "mypy == 1.0.0",
    "pre-commit == 3.5.0"
]

[tool.mypy]
python_version = "3.10"
